TIMEOUT: 5
VERBOSE: yes
SERIAL: yes
SERIAL_BAUDRATE: 115200

/01 Hello (debugcon)
    PROTOCOL: limine
    KERNEL_PATH: boot():/boot/01_hello.elf

/02 Framebuffer Info
    PROTOCOL: limine
    KERNEL_PATH: boot():/boot/02_fbinfo.elf

/03 Fill Screen (red)
    PROTOCOL: limine
    KERNEL_PATH: boot():/boot/03_fill.elf

/04 Color Gradient
    PROTOCOL: limine
    KERNEL_PATH: boot():/boot/04_gradient.elf

/05 Draw Text (HELLO!)
    PROTOCOL: limine
    KERNEL_PATH: boot():/boot/05_text.elf
